version: '3'
services:
  node-app:
    restart: always
    build:
      context: ./server
    # ports:
    #   - "3000:3000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "4000:80"
    links:
      - node-app  
    depends_on:
      - node-app     