version: '3'
services:
  node-app:
    restart: always
    build:
      context: ./server
    links:
      - app-mongo  
    # ports:
    #   - "3000:3000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "4000:80"
    links:
      - node-app  
    depends_on:
      - node-app   
  app-mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes:
  data:
    driver: local      